[build]
  publish   = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

[dev]
  framework = "#static"
  publish = "."
  functions = "netlify/functions"
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/api/dlq-retry"
  to   = "/.netlify/functions/dlq-retry-http"
  status = 200

[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/openai-chat"
  status = 200

[[redirects]]
  from = "/api/moderate"
  to   = "/.netlify/functions/moderate"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self';"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
