[build]
  command = "npm run build && [ -f src/_redirects ] && cp src/_redirects dist/_redirects || true"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "netlify dev"
  targetPort = 8888
  framework = "custom"

# Context: Production
[context.production.environment]
  NODE_VERSION = "22"
  BASE_URL = "https://cxis.today"
  LOG_LEVEL = "error"
  ATS_WEBHOOK_SECRET = "${ATS_WEBHOOK_SECRET}"
  SCORE_TOKENS = "${SCORE_TOKENS}"

# Context: Staging
[context.staging.environment]
  NODE_ENV = "staging"
  BASE_URL = "https://staging--cxis.netlify.app"
  LOG_LEVEL = "debug"
  ATS_WEBHOOK_SECRET = "${ATS_WEBHOOK_SECRET}"
  SCORE_TOKENS = "${SCORE_TOKENS}"

# Context: Deploy Previews
[context.deploy-preview.environment]
  NODE_ENV = "preview"
  BASE_URL = "https://deploy-preview--cxis.netlify.app"
  LOG_LEVEL = "info"
  ATS_WEBHOOK_SECRET = "${ATS_WEBHOOK_SECRET}"
  SCORE_TOKENS = "${SCORE_TOKENS}"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-checklinks"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-debug-cache"

[[plugins]]
  package = "netlify-plugin-snyk"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[[plugins]]
  package = "netlify-plugin-html-validate"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-no-more-404"

[functions]
  node_bundler = "esbuild"

[headers]
  [[headers]]
    for = "/.netlify/functions/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
