# Netlify config for static Eleventy site + Netlify Functions (deterministic)

[build]
  command  = "npm run build"
  publish  = "dist"

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION  = "10"

[dev]
  framework  = "#static"
  publish    = "src"
  functions  = "netlify/functions"
  port       = 8888
  autoLaunch = false

# Security/CORS headers (adjust if needed)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-store"

# Example scheduled functions (cron). Keep schedules in Functions (not Edge).
[functions."nudge-cron"]
  schedule = "*/30 * * * *"

[functions."dlq-retry-cron"]
  schedule = "*/15 * * * *"
