name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run build || true
      - run: npm test
      - name: Reliability (with Netlify Dev)
        run: |
          npx netlify dev --port 8888 --dir dist --functions netlify/functions &
          DEV_PID=$!
          sleep 3
          npm run test:reliability
          kill $DEV_PID || true
