name: Run Demo (Netlify Dev + Tests)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: run-demo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Netlify CLI + wait-on (specific version to avoid edge functions issues)
        run: npm install -D netlify-cli@17.34.2 wait-on

      - name: Start Netlify Dev (background)
        run: |
          npx netlify dev --dir dist --functions netlify/functions --port 8888 --offline --no-open > netlify-dev.log 2>&1 &
          echo $! > netlify_dev.pid
        env:
          NODE_ENV: test

      - name: Wait for server
        run: npx wait-on http://localhost:8888 --timeout 60000

      - name: Run tests
        env:
          BASE_URL: http://localhost:8888
        run: |
          node test/test-quality.js
          node test/test-ats.js
          node test/test-reliability.js

      - name: Stop Netlify Dev (always)
        if: always()
        run: |
          kill -9 $(cat netlify_dev.pid) 2>/dev/null || true
          sleep 1
          echo "::group::Netlify Dev Log"
          head -n 200 netlify-dev.log || true
          echo "::endgroup::"

      - name: Upload logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: netlify-dev-log
          path: netlify-dev.log